var restList = (function () {
    var rest = [
        {
			name:"Café Italia",
			date:["yes", "no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"bright",
			vol:"loud",
			parking:"yes",
			Tel: "03-5612888",
			Address: "Kremintzki 6",
			Site: "http://www.mouse.co.il/CM.food_item_place,382,213,8464,.aspx"
		},
		{
			name:"Brasserie",
			date:["no"],
			so:["friends", "family", "business"],
			sitting:["table"],
			light:"bright",
			vol:"loud",
			parking:"valet",
			Tel: "03-6967111",
			Address: "Ibn Gabirol 70",
			Site: "http://www.brasserie.co.il/"
		},
		{
			name:"Mizlala",
			date: ["yes", "no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"quiet",
			parking:"no",
			Tel: "03-5665505",
			Address: "Nahalat Binyamin 57",
			Site: "http://www.mizlala.co.il"
		},
		{
			name:"Cantina",
			date:["no"],
			so:["friends", "family", "business"],
			sitting:["table"],
			light:"dim",
			vol:"quiet",
			parking:"yes",
			Tel: "03-6205051",
			Address: "Rothschild 71",
			Site: "http://www.mouse.co.il/CM.food_item_place,382,213,4178,.aspx"
		},
		{
			name:"Catit",
			date: ["yes"],
			so:[""],
			sitting:["table"],
			light:"bright",
			vol:"quiet",
			parking:"yes",
			Tel: "03-5107001",
			Address: "Heichal HaTalmud 4",
			Site: "http://www.catit.co.il/"
		},
		{
			name:"Yafo Tel-Aviv",
			date: ["yes", "no"],
			so:["family"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"quiet",
			parking:"yes",
			Tel: "03-6249249",
			Address: "Yigal Alon 98",
			Site: "http://www.yaffotelaviv.com/"
		},
		{
			name:"Messa",
			date: ["yes", "no"],
			so:["business"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"quiet",
			parking:"yes",
			Tel: "03-6856859",
			Address: "HaArba'a 19",
			Site: "http://www.messa.co.il"
		},
		{
			name:"Joya",
			date:["no"],
			so:["friends", "family", "business"],
			sitting:["bar", "table"],
			light:"bright",
			vol:"quiet",
			parking:"yes",
			Tel: "03-6425854",
			Address: "HaArba'a 5",
			Site: "http://www.joya.co.il/he/home/default.aspx"
		},
		{
			name:"Herbert Samuel",
			date: ["yes", "no"],
			so:["family", "tourists", "business"],
			sitting:["table"],
			light:"dim",
			vol:"quiet",
			parking:"yes",
			Tel: "03-5166516",
			Address: "Kaufmann 6",
			Site: "http://herbertsamuel.co.il/default.asp?PageID=5"
		},
		{
			name:"Raphael",
			date:["no"],
			so:["friends", "family", "business", "tourists"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"quiet",
			parking:"yes",
			Tel: "03-5226464",
			Address: "Yarkon 87",
			Site: "http://raphaeltlv.co.il/"
		},
		{
			name:"Onami",
			date: ["yes", "no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"bright",
			vol:"quiet",
			parking:"yes",
			Tel: "03-5621172",
			Address: "HaArba'a 18",
			Site: "http://www.onami.co.il/he/home/default.aspx"
		},
		{
			name:"Tapeo",
			date: ["yes", "no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"loud",
			parking:"yes",
			Tel: "03-6240484",
			Address: "HaArba'a 16",
			Site: "http://www.tapeo.co.il/he/TLV/home.aspx"
		},
		{
			name:"Turkiz",
			date: ["yes", "no"],
			so:["friends", "family", "tourists"],
			sitting:["bar", "table"],
			light:"bright",
			vol:"loud",
			parking:"yes",
			Tel: "03-6996306",
			Address: "Rosenblum 6",
			Site: "http://www.turkiz-rest.co.il/"
		},
		{
			name:"Boya",
			date:["no"],
			so:["friends", "family", "tourists"],
			sitting:["table"],
			light:"bright",
			vol:"quiet",
			parking:"yes",
			Tel: "03-5446166",
			Address: "HaTa'arucha 3",
			Site: "http://www.boya.co.il/"
		},
		{
			name:"Dallal",
			date:["no"],
			so:["friennds", "family"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"quiet",
			parking:"yes",
			Tel: "03-5109292",
			Address: "Shabazi 10",
			Site: "http://www.dallal.info/restIndex3.asp?pageId=31"
		},
		{
			name:"Suzanna",
			date:["no"],
			so:["friends", "family", "tourists"],
			sitting:["table"],
			light:"bright",
			vol:"loud",
			parking:"yes",
			Tel: "03-5177580",
			Address: "Shabazi 9",
			Site: "http://www.mouse.co.il/CM.food_item_place,383,213,5644,.aspx"
		},
		{
			name:"Social Club",
			date: ["yes", "no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"loud",
			parking:"no",
			Tel: "03-5601114",
			Address: "Rothschild 45",
			Site: "http://socialclub.rest.co.il/he/home/default.aspx"
		},
		{
			name:"Makom Shel Basar",
			date:["no"],
			so:["friends", "family"],
			sitting:["table"],
			light:"dim",
			vol:"quiet",
			parking:"no",
			Tel: "03-5104020",
			Address: "Shabazi 64",
			Site: "http://www.mouse.co.il/CM.Food_Item_Place,382,213,7938,.aspx"
		},
		{
			name:"Vicki Cristina",
			date: ["yes", "no"],
			so:["friends", "family", "tourists"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"loud",
			parking:"yes",
			Tel: "03-7367272",
			Address: "Kaufmann 2",
			Site: "http://www.vicky-cristina.co.il/"
		},
		{
			name:"Abraxas North",
			date: ["yes", "no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"loud",
			parking:"no",
			Tel: "03-5166660",
			Address: "Lilienblum 40",
			Site: "http://www.abraxas.co.il/"
		},
		{
			name:"Zepra",
			date: ["yes", "no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"quiet",
			parking:"yes",
			Tel: "03-6240044",
			Address: "Yigal Alon 96",
			Site: "http://zepra.co.il/"
		},
		{
			name:"Nanuchka",
			date: ["yes", "no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:	"dim",
			vol:"loud",
			parking:"no",
			Tel: "03-5162254",
			Address: "Lilienblum 30",
			Site: "https://www.facebook.com/nanuchkatlv"
		},
		{
			name:"Port Said",
			date:["no"],
			so:["friends"],
			sitting:["table"],
			light:"bright",
			vol:"loud",
			parking:"yes",
			Tel: "03-6207436",
			Address: "Ha Sinai 2",
			Site: "https://www.facebook.com/pages/Port-Said/193302427463816"
		},
		{
			name:"Kalamata",
			date: ["yes", "no"],
			so:["friends", "family", "tourists"],
			sitting:["table"],
			light:"dim",
			vol:"quiet",
			parking:"no",
			Tel: "03-6819998",
			Address: "Kikar Kdumim 10, Yafo",
			Site: "http://www.kalamata.co.il/"
		},
		{
			name:"Hotel Monefiore",
			date: ["yes", "no"],
			so:["business"],
			sitting:["table"],
			light:"dim",
			vol:"quiet",
			parking:"no",
			Tel: "03-5646100",
			Address: "Montefiore 36",
			Site: "http://www.hotelmontefiore.co.il/restaurant"
		},
		{
			name:"Elba",
			date: ["yes"],
			so:[""],
			sitting:["bar", "table"],
			light:"dim",
			vol:"quiet",
			parking:"yes",
			Tel: "03-5467905",
			Address: "Ibn Gabirol 36",
			Site: "https://www.facebook.com/ELBA.RESTAURANT"
		},
		{
			name:"Café Europa",
			date: ["yes", "no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"loud",
			parking:"yes",
			Tel: "03-5259987",
			Address: "Rothschild 9",
			Site: "http://www.mouse.co.il/CM.food_item_place,382,213,11158,.aspx"
		},
		{
			name:"Hatzer Goldman",
			date:["no"],
			so:["friends", "family", "tourists"],
			sitting:["table"],
			light:"bright",
			vol:"loud",
			parking:"no",
			Tel: "03-6822111",
			Address: "Goldman 6",
			Site: "http://www.goldmanc.co.il/home.php"
		},
		{
			name:"Shila",
			date: ["yes", "no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"loud",
			parking:"valet",
			Tel:"03-5221224",
			Address: "Ben Yehuda 182",
			Site: "http://www.shila-rest.co.il/"
		},
		{
			name:"Tapas 1 ha'am",
			date: ["yes", "no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"loud",
			parking:"valet",
			Tel: "03-5666966",
			Address: "Ehad Ha'am 27",
			Site: "http://herbertsamuel.co.il/default.asp?PageID=6"
		},
		{
			name:"Sola",
			date: ["yes"],
			so:[""],
			sitting:["bar", "table"],
			light:"dim",
			vol:"quiet",
			parking:"no",
			Tel: "03-5499626",
			Address: "Beit Eshel 31",
			Site: "https://www.facebook.com/pages/Sola-Food-Wine-Bar/247225912061993"
		},
		{
			name:"Taizu",
			date: ["yes", "no"],
			so:["family", "friends"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"loud",
			parking:"no",
			Tel: "03-5225005",
			Address: "Begin 23",
			Site: "https://www.facebook.com/TaizuRestaurant"
		},
		{
			name:"Juz & Luz",
			date: ["yes"],
			so:[""],
			sitting:["bar", "table"],
			light:"dim",
			vol:"quiet",
			parking:"no",
			Tel: "03-5606385",
			Address: "Yehuda Halevi 51",
			Site: "http://www.mouse.co.il/CM.Food_Item_Place,384,213,3988,.aspx"
		},
		{
			name:"Toto",
			date: ["yes", "no"],
			so:["family", "friends"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"loud",
			parking:"yes",
			Tel: "03-6935151",
			Address: "Berkovich 4",
			Site: "http://www.toto-rest.co.il/"
		},
		{
			name:"Mel & Michelle",
			date: ["yes"],
			so:[""],
			sitting:["bar", "table"],
			light:"dim",
			vol:"quiet",
			parking:"yes",
			Tel: "03-5293232",
			Address: "Ben Yehuda 155",
			Site: "http://www.mel-michelle.co.il/"
		},
		{
			name:"Mitbach Laila",
			date: ["yes", "no"],
			so:["friends"],
			sitting:["bar"],
			light:"dim",
			vol:"loud",
			parking:"no",
			Tel: "03-5660481",
			Address: "Lilienblum 43",
			Site: "http://www.nightkitchen.co.il/"
		},
		{
			name:"Yassou",
			date:["no"],
			so:["friends"],
			sitting:["bar", "table"],
			light:"bright",
			vol:"loud",
			parking:"no",
			Tel: "03-6031719",
			Address: "Yarkon 105",
			Site: "http://www.yassoutelaviv.co.il/"
		},
		{
			name:"Flee Market",
			date:["no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"bright",
			vol:"loud",
			parking:"no",
			Tel: "03-6202262",
			Address: "Rabbi Yohanan 8",
			Site: "https://www.facebook.com/pages/Fleamarket-Restaurant-%D7%9E%D7%A1%D7%A2%D7%93%D7%AA-%D7%A4%D7%9C%D7%99%D7%9E%D7%A8%D7%A7%D7%98/105537962947115"
		},
		{
			name:"Kitchen Market",
			date:["no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"bright",
			vol:"loud",
			parking:"paid",
			Tel: "03-5446669",
			Address: "Hangar 12, Nemal Tel Aviv",
			Site: "http://www.kitchen-market.co.il/"
		},
		{
			name:"Alma",
			date: ["yes"],
			so:[""],
			sitting:["bar", "table"],
			light:"dim",
			vol:"quiet",
			parking:"no",
			Tel: "03-6308777",
			Address: "Yavne 23",
			Site: "http://www.almahotel.co.il/alma-lounge-dining"
		},
		{
			name:"HaShulchan",
			date:["no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"bright",
			vol:"loud",
			parking:"no",
			Tel: "03-5257171",
			Address: "Rothschild 73",
			Site: "http://www.mouse.co.il/CM.food_item_place,382,213,10774,.aspx"
		},
		{
			name:"Popina",
			date: ["yes", "no"],
			so:["friends", "family"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"quiet",
			parking:"valet",
			Tel: "03-5757477",
			Address: "Ehad Ha'am 3",
			Site: "https://www.facebook.com/PopinaTelAviv"
		},
		{
			name:"Cocina Tamar",
			date: ["yes", "no"],
			so:["friends", "family"],
			sitting:["table"],
			light:"bright",
			vol:"quiet",
			parking:"yes",
			Tel: "03-6390407",
			Address: "HaTsfira 10",
			Site: "http://www.mouse.co.il/CM.Food_Item_Place,382,213,4033,.aspx"
		},
		{
			name:"Coffee Bar",
			date: ["yes", "no"],
			so:["family", "Friends", "Business"],
			sitting:["bar", "table"],
			light:"bright",
			vol:"quiet",
			parking:"no",
			Tel: "03-6889696",
			Address: "Yad Haruzim 13",
			Site: "http://www.coffeebar.co.il/"
		},
		{
			name:"Radio Rosco",
			date: ["yes", "no"],
			so:["Family", "Friends", "Business"],
			sitting:["table"],
			light:"bright",
			vol:"loud",
			parking:"no",
			Tel: "03-5600334",
			Address: "Allenby 97",
			Site: "https://www.facebook.com/pages/%D7%A8%D7%93%D7%99%D7%95-%D7%A8%D7%95%D7%A1%D7%A7%D7%95-%D7%A7%D7%A4%D7%99%D7%98%D7%A8%D7%99%D7%94-%D7%90%D7%99%D7%98%D7%9C%D7%A7%D7%99%D7%AA/159061699052"
		},
		{
			name:"Cheder Ochel",
			date:["no"],
			so:	["friends"],
			sitting:["table"],
			light:"bright",
			vol:"loud",
			parking:"paid",
			Tel: "03-6966188",
			Address: "Shaul Hamelech 23",
			Site: "https://www.facebook.com/dininghall"
		},
		{
			name:"Vong",
			date:["no"],
			so:	["family", "friends"],
			sitting:["bar","table"],
			light:"bright",
			vol:"loud",
			parking:"paid",
			Tel: "03-6337171",
			Address: "Rothschild 15",
			Site: "http://www.vong.co.il"
		},
    {
			name:"Pronto",
			date: ["yes", "no"],
			so:	["friends, family, business"],
			sitting:["bar", "table"],
			light:"dim",
			vol:"loud",
			parking:"paid",
			Tel: "03-5660915",
			Address: "Herzel 4",
			Site: "http://www.pronto.co.il/"
		},
	{
			name:"Yakimono",
			date: ["yes", "no"],
			so:	["friends", "family"],
			sitting:["bar","table"],
			light:"dim",
			vol:"quiet",
			parking:"paid",
			Tel: "03-5175171",
			Address: "Rothschild 19",
			Site: "http://www.yakimono.co.il"
		},
		{
			name:"Mul-Yam",
			date: ["yes", "no"],
			so:	["family", "business", "tourists"],
			sitting:["table"],
			light:"dim",
			vol:"quiet",
			parking:"paid",
			Tel: "03-5469920",
			Address: "Hangar 24, Namal Tel Aviv",
			Site: "http://www.mulyam.com/"
		},
		{
			name:"Sardinia",
			date: ["yes", "no"],
			so:	["family", "friends", "tourists"],
			sitting:["bar","table"],
			light:"bright",
			vol:"loud",
			parking:"paid",
			Tel: "03-6832211",
			Address: "Kikar Kdumim, Yafo",
			Site: "https://www.facebook.com/SardiniaItalianTrattoria"
		},
		{
			name:"Adora",
			date: ["yes", "no"],
			so:	["friends","family"],
			sitting:["bar","table"],
			light:"dim",
			vol:"quiet",
			parking:"no",
			Tel: "03-6050896",
			Address: "Ben Yehuda 226",
			Site: "http://www.mouse.co.il/CM.Food_Item_Place,382,213,3926,.aspx"
		},
		{
			name:"David veYosef",
			date: ["yes", "no"],
			so:["friends"],
			sitting:["bar","table"],
			light:"dim",
			vol:"loud",
			parking:"valet",
			Tel: "03-6040036",
			Address: "Montefiore 21",
			Site: "http://davidveyossef.co.il/"
		}
	];


    function getList(){
        return rest;
    }

    return {
        getList:getList

    }

})();
